### ISSUE TITLE
What does 'uid' stands for?

### ISSUE THREAD

**Issue by iamhealthy** [whchenlab/mBodymap#1]
Hi,

I have downloaded two files (i.e. mbodymap_relative_species_abundances.csv and  mbodymap_species_to_samples_relative_abundance.csv) from the website of mBodymap.

There are 'uid' in the column names.

Could you please clarify: what does 'uid' stands for?

Thanks in advance.
![屏幕截图 2022-04-19 160527](https://user-images.githubusercontent.com/15224600/163955649-4752faa9-5213-4844-8814-b585e8bd7668.jpg)

**Comment by pcty-kk** [comment]
mbodymap_species_to_samples_relative_abundance.uid = mbodymap_loaded_samples.id
mbodymap_loaded_samples.accession_id = mbodymap_samples.run_id 
you can download these two table in "Help" page of mBodymap(https://mbodymap.microbiome.cloud/#/help) 
 [All runs table](https://mbodymap.microbiome.cloud/Downloads/mbodymap_samples.zip) and
[Processed runs](https://mbodymap.microbiome.cloud/Downloads/mbodymap_loaded_samples.zip)

Sorry for late reply~
