### ISSUE TITLE
relative_abundance: 100

### ISSUE THREAD

**Issue by iamhealthy** [whchenlab/mBodymap#2]
Hi friends:

I downloaded 'mbodymap_species_to_samples_relative_abundance.csv' from the ***Help*** panel of the website of ***mBodymap*** [link](https://mbodymap.microbiome.cloud/Downloads/mbodymap_species_to_samples_relative_abundance.zip).

I noticed that there are 243 rows out of 6687650 rows showing the relative abundance of **100**. 
### _**Does this mean that the microbiota is dominated exclusively by a singular species?**_

Below is a snapshop of some rows.
![屏幕截图 2022-04-20 145804](https://user-images.githubusercontent.com/15224600/164169095-bd0ba53f-4e5c-4e9c-8f5b-55231c28aafe.jpg)

**Comment by pcty-kk** [comment]
yes, I checked some runs like SRR5189090、SRR5189108、SRR640870, there is only one species was identified.
